---
abstract: 'Catalyst based application'
author:
  - 'Devin Austin'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OTBAN
no_index:
  directory:
    - inc
    - t
requires:
  Cache::Memcached: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Controller::HTML::FormFu: 0
  Catalyst::Controller::REST: 0
  Catalyst::Model::KiokuDB: 0
  Catalyst::Plugin::Cache: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.71000
  Catalyst::View::Email: 0
  Config::General: 0
  KiokuDB: 0
  Moose: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
